version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      routine-github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      routine-go-modules:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: terraform
    directories:
      - /
      - /infra/**
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      routine-terraform:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
